# Default AmForth 32-bit configuration

.equ YES , 1
.equ NO  , 0

# what Forth word groups do you want included in the core
.equ WANT_SEARCH_ORDER , YES 
.equ WANT_FLOAT , NO

.equ WANT_CASE         , NO
.equ WANT_MATCH        , NO
.equ WANT_FORNEXT      , NO

.equ WANT_SEE          , NO
.equ WANT_SAVE         , NO

.equ WANT_CODE         , NO
.equ WANT_TABLE        , NO

# Other configuration parameters
.equ WANT_USB_OPERATOR , NO
.equ WANT_QEM_BUILD , NO
