/*
    Use AGT0 timer as an interrupt source.
 */

/*
    RA4M1 Group: User Manual: 23. Low Power Asynchronous General Purpose Timer (AGT)
 */
.equ RA4_AGT0_AGT, 0x40084000 /* AGT0 Counter Register [15:0] R/W */
.equ RA4_AGT1_AGT, 0x40084100 /* AGT1 Counter Register [15:0] R/W */
.equ RA4_AGT0_AGTCMA, 0x40084002 /* AGT0 Compare Match A Register [15:0] R/W */
.equ RA4_AGT1_AGTCMA, 0x40084102 /* AGT1 Compare Match A Register [15:0] R/W */
.equ RA4_AGT0_AGTCMB, 0x40084004 /* AGT0 Compare Match B Register [15:0] R/W */
.equ RA4_AGT1_AGTCMB, 0x40084104 /* AGT1 Compare Match B Register [15:0] R/W */
.equ RA4_AGT0_AGTCR, 0x40084008 /* AGT0 Control Register */
.equ RA4_AGT1_AGTCR, 0x40084108 /* AGT1 Control Register */
/*
    [0] TSTART  Count Start R/W
    [1] TCSTF   Count Status Flag R
    [2] TSTOP   Count Forced Stop W=1
    [4] TEDGF   Active Edge Judgement Flag R/(W)
    [5] TUNDF   Undeflow Flag R/(W)
    [6] TCMAF   Compare Match A Flag R/(W)
    [7] TCMBF   Compare Match B Flag R/(W)
    (W) - only 0 can be written to clear the flag
 */
 .equ RA4_AGT0_AGTMR1, 0x40084009 /* AGT0 Mode Register 1 */
 .equ RA4_AGT1_AGTMR1, 0x40084109 /* AGT1 Mode Register 1 */
 /*
    [2:0]   TMOD    Operating mode R/W  000=Timer, 001=Pulse output, 010=Event Counter, 011=Pulse Width Msr, 100=Pulse Period Msr
    [3]     TEDGPL  Edge Polarity R/W
    [6:4]   TCK     Count Source    000=PCKLB, 001=PCKLB/8, 011=PCKLB/2, 100=AGTLCLK, 101=AGT0 underflow, 110=AGTSCLK
  */
.equ RA4_AGT0_AGTMR2, 0x4008400A /* AGT0 Mode Register 2 */
.equ RA4_AGT1_AGTMR2, 0x4008410A /* AGT1 Mode Register 2 */
/*
    [2:0]   CKS AGTLCLK/AGTSCLK divisor R/W n => 1/2^n
    [7]     LPM Low Power Mode R/W  0=normal, 1=low power

    AGTLCLK is generated by LOCO, AGTSCLCK is not available on UNO R4 (no SOSC)
 */
.equ RA4_AGTO_AGTIOC, 0x4008400C /* AGT0 I/O Control Register */
.equ RA4_AGT1_AGTIOC, 0x4008410C /* AGT1 I/O Control Register */
.equ RA4_AGTO_AGTISR, 0x4008400D /* AGT0 Event Pin Select Register */
.equ RA4_AGT1_AGTISR, 0x4008410D /* AGT1 Event Pin Select Register */
.equ RA4_AGTO_AGTCMSR, 0x4008400E /* AGT0 Compare Match Function Select Register */
.equ RA4_AGT1_AGTCMSR, 0x4008410E /* AGT1 Compare Match Function Select Register */
.equ RA4_AGTO_AGTIOSEL, 0x4008400F /* AGT0 Pin Select Register */
.equ RA4_AGT1_AGTIOSEL, 0x4008410F /* AGT1 Pin Select Register */

.equ INT_AGT0, 0 @ AGT0 interrupt number

CODEWORD "agt0.init", AGT0_INIT /* ( u -- ) initialize AGT0 as millisecond counter to generate interrupt every u ms */
    @ enable interrupt in NVIC
    ldr r0, =ARM_NVIC_ISER
    mov r1, 1<<INT_AGT0 @ bitmask for the interrupt number
    str r1, [r0] @ set the bit in ISER
    ldr r0, =RA4_ICU_IELSR
    mov r1, #0x1e @ set AGT0_AGTI as event trigger for the interrupt
    str r1, [r0, INT_AGT0<<2] @ IELSR offset from the interrupt number
    ldr r0, =RA4_AGT0_AGTMR1
    mov r1, #0x40 @ Timer mode with AGTLCLK 32kHz
    strb r1, [r0]
    ldr r0, =RA4_AGT0_AGTMR2
    mov r1, #0x05 @ 1/32 clock divisor => ~ 1ms tick
    strb r1, [r0]
    ldr r0, =RA4_AGT0_AGT
    strb TOS, [r0] @ set interrupt period to u1 milliseconds
    loadtos
    NEXT
END AGT0_INIT

CODEWORD "agt0.start", AGT0_START /* ( -- ) start the interrupt timer */
    ldr r0, =RA4_AGT0_AGTCR
    mov r1, #1 @ TSTART = 1
    str r1, [r0]
    NEXT
END AGT0_START

CODEWORD "agt0.stop", AGT0_STOP /* ( -- ) stop the interrupt timer */
    ldr r0, =RA4_AGT0_AGTCR
    mov r1, #1 @ TSTART = 0
    str r1, [r0]
    NEXT
END AGT0_STOP

.thumb_func
led_handler: /* flip the LED state, assume LED is initialized as per led.s */
    ldr r0, =RA4_P102PFS
    ldrb r1, [r0] @ read PODR bit
    eor r1, #1  @ flip PODR bit
    strb r1, [r0]
    bx lr
