name: ARM Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # See https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads
      VERSION: 15.2.rel1
      TOOLS_DIR: toolchain
    steps:
      - uses: actions/checkout@v4

      - name: Cache Toolchain Installation
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: ${{ env.TOOLS_DIR }}
          key: ${{ runner.os }}-${{ env.VERSION }}

      - name: Install ARM GNU Toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: |
          # Define installation path and toolchain archive name

          ARCHIVE=arm-gnu-toolchain-$VERSION-x86_64-arm-none-eabi.tar.xz
          URL=https://developer.arm.com/-/media/Files/downloads/gnu/$VERSION/binrel/$ARCHIVE

          mkdir -p $TOOLS_DIR
          # Download and extract the toolchain (adjust URL/filename as needed)
          curl -L $URL | tar -xJ -C $TOOLS_DIR --strip-components=1

      - name: Add toolchain binaries to the PATH
        run:  echo "$GITHUB_WORKSPACE/$TOOLS_DIR/bin" >> $GITHUB_PATH

      - name: Verify installation
        run:  arm-none-eabi-as --version

      - name: Build RA4M1
        run: |
          cd arm/mcu/ra4m1
          echo $PATH
          arm-none-eabi-as --version
          make

      - name: Build LM4F120
        run: cd arm/mcu/lm4f120 && make

      - name: Build Linux/RaspPi
        run: cd arm/mcu/linux && make